targets:
  $default:
    builders:
      freezed:freezed:
        generate_for:
          include:
            - lib/**.codegen.dart
      json_serializable:json_serializable:
        generate_for:
          include:
            - lib/**.codegen.dart
      envied_generator:envied:
        generate_for:
          include:
            - lib/env/cloud_env_test.codegen.dart
            - lib/env/env.codegen.dart
