name: CI
on:
  push:
    branches:
      - 'main'
      - 'feature/github_action_cache'
  pull_request:
    branches: [main]
jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo
            frontend/rust-lib/target
          key: ${{ runner.os }}-rust-${{ hashFiles('./frontend/rust-lib/Cargo.toml') }}
      
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      
      - name: Checkout Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Deps
        working-directory: frontend
        run: |
          cargo install --force cargo-make
          cargo install --force duckscript_cli
          cargo make flowy_dev
          echo PATH="$PATH":"$HOME/.pub-cache/bin" >> $GITHUB_PATH
      
      - name: Build
        working-directory: frontend
        run: |
          flutter config --enable-macos-desktop
          cargo make --profile production-mac-x86 appflowy
  
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo
            frontend/rust-lib/target
          key: ${{ runner.os }}-rust-${{ hashFiles('./frontend/rust-lib/Cargo.toml') }}
      
      - name: Packages
        run: |
          sudo wget -qO /etc/apt/trusted.gpg.d/dart_linux_signing_key.asc https://dl-ssl.google.com/linux/linux_signing_key.pub
          sudo wget -qO /etc/apt/sources.list.d/dart_stable.list https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list
          sudo apt-get update
          sudo apt-get install -y dart curl build-essential libsqlite3-dev libssl-dev clang cmake ninja-build pkg-config libgtk-3-dev
      
      - name: Setup environment - Rust and Cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      
      - name: Setup environment - Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Deps
        working-directory: frontend
        run: |
          cargo install --force cargo-make
          cargo install --force duckscript_cli
          cargo make flowy_dev
          echo PATH="$PATH":"$HOME/.pub-cache/bin" >> $GITHUB_PATH
      
      - name: Build
        working-directory: frontend
        run: |
          flutter config --enable-linux-desktop
          cargo make --profile production-linux-x86 appflowy
