name: FlowyEditor test

on:
  push:
    branches:
      - "main"
      - "codecov"

  pull_request:
    branches:
      - "main"

env:
  CARGO_TERM_COLOR: always


jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.0.5"
          cache: true

      - name: Run FlowyEditor tests
        working-directory: frontend/app_flowy/packages/appflowy_editor
        run: |
          flutter pub get
          flutter test --coverage

          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov
