name: Sign

on:
  workflow_dispatch:

jobs:
  build:
      runs-on: macos-latest
      steps:
        - name: Download
          run: curl -L https://github.com/LucasXu0/AppFlowy/releases/download/0.2.9/AppFlowy.zip -o AppFlowy.zip
        - name: Unzip
          run: unzip AppFlowy.zip
        - name: Codesign executable
          run: |
            echo ${{ secrets.MACOS_CERTIFICATE }} | base64 --decode > certificate.p12
            security create-keychain -p action build.keychain
            security default-keychain -s build.keychain
            security unlock-keychain -p action build.keychain
            security import certificate.p12 -k build.keychain -P ${{ secrets.MACOS_CERTIFICATE_PWD }} -T /usr/bin/codesign
            security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k action build.keychain
            /usr/bin/codesign --force --options runtime --deep --sign "Developer ID Application: APPFLOWY PTE. LTD (VHB67HRSZG)" AppFlowy.app -v
        - name: Create macOS dmg
          run: |
            brew install create-dmg
            create-dmg \
            --volname AppFlowy.dmg \
            --hide-extension "AppFlowy.app" \
            --window-size 600 450 \
            --app-drop-link 458 249 \
            "AppFlowy.dmg" \
            "AppFlowy.app"
        - name: notarytool
          run: |
            xcrun notarytool submit AppFlowy.dmg --apple-id ${{ secrets.MACOS_NOTARY_USER }} --team-id ${{ secrets.MACOS_TEAM_ID }} --password ${{ secrets.MACOS_NOTARY_PWD }} -v -f "json" --wait
        - name: Upload
          uses: actions/upload-artifact@v3
          with:
            name: AppFlowy
            path: AppFlowy.dmg